
[profile.default]
solc_version = "0.8.15"
ffi = true
remappings = [
    'ds-test/=lib/ds-test/src/',
    'solmate/=lib/solmate/src/',
    'forge-std/=lib/forge-std/src/',
    'test-utils/=lib/test-utils/src/',
    'prb-test/=lib/prb-test/src/'
]
